# -*- coding: utf-8 -*-
"""
/***************************************************************************
 POSExport
                                 A QGIS plugin
 Plugin para exportar LINHA+DEM para arquivos .pos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-11
        copyright            : (C) 2026 by Jao F
        email                : joaaao05@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load POSExport class from file POSExport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pos_export import POSExport
    return POSExport(iface)
