# -*- coding: utf-8 -*-
"""
/***************************************************************************
 POSExport
                                 A QGIS plugin
 Plugin para exportar LINHA+DEM para arquivos .pos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-09-11
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Jao F
        email                : joaaao05@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication
from qgis.core import QgsSettings
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject, QgsMapLayerType, QgsVectorLayer
from qgis.PyQt.QtWidgets import QFileDialog
from qgis.core import QgsProcessingFeatureSourceDefinition


# Import the code for the dialog
from .pos_export_dialog import POSExportDialog
import os.path
import json
import processing


class POSExport:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&POSITION Export')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('POSExport', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Exportar arquivo .pos'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&POSITION Export'),
                action)
            self.iface.removeToolBarIcon(action)

    def selecionar_arquivo(self):

        arquivo, _ = QFileDialog.getSaveFileName(
            self.dlg,
            "Salvar resultado",
            "",
            "POSITION (*.pos)"
        )

        if arquivo:
            self.dlg.lineEditArquivo.setText(arquivo)

    def GerarPos(self, arquivo_json, arquivo_pos):
        # Carrega o JSON
        with open(arquivo_json, "r", encoding="utf-8") as f:
            dados = json.load(f)

        # Se o JSON for GeoJSON FeatureCollection
        if "features" in dados:
            features = dados["features"]
        else:
            # Caso seja lista simples de features
            features = dados

        linhas_saida = []
        estaca = 0

        first_normalize = 0.2
        sec_normalize = 0.1

        last = len(features)-1

        z_array = []

        for feature in features:
            props = feature["properties"]
            coords = feature["geometry"]["coordinates"]

            z_array.append(coords[2])


        for i in range(len(features)):
            props = features[i]["properties"]
            coords = features[i]["geometry"]["coordinates"]

            x = coords[0]
            y = coords[1]
            #z = coords[2]
            

            if(i == 0 or i == 1 or i == len(features)-2 or i == len(features)-1):
                z = coords[2]
            else:
                zin = coords[2]
                #z = zin
                difffor = ((zin - z_array[i+1])*first_normalize) + ((zin - z_array[i+2])*sec_normalize)
                diffback =  ((zin - z_array[i-1])*first_normalize) + ((zin - z_array[i-2])*sec_normalize)
                diff = 0

                diff = (difffor*-1) + (diffback*-1)
                
                z = zin + diff

                coords[2] = z

            
            # Campo "1"
            valor = props.get("1", 0)

            # Converte ponto para vírgula
            x_str = str(x).replace(".", ",")
            y_str = str(y).replace(".", ",")
            z_str = f"{(z):.3f}".replace(".", ",")

            # Exemplo: 569 -> 569,0
            valor_str = f"{float(valor):.1f}".replace(".", ",")

            linha = f"{x_str};{y_str};{z_str};{estaca};0;0;0;4;4;;"
            linhas_saida.append(linha)

            estaca = estaca + 1

            # Salva arquivo .pos
            with open(arquivo_json, "w", encoding="utf-8") as f:
                json.dump(dados, f, ensure_ascii=False, indent=4)

            with open(arquivo_pos, "w", encoding="utf-8") as f:
                f.write("\n".join(linhas_saida))

        

    def getGJPath(self, path):
        name, format = os.path.splitext(path)
        return name + ".geojson"


    def run(self):
      
        if self.first_start == True:
            self.first_start = False
            self.dlg = POSExportDialog()

            self.dlg.pushButtonArquivo.clicked.connect(
                self.selecionar_arquivo
            )


        self.dlg.comboBoxCamada.clear()

        self.dlg.comboBoxDEM.clear()

        self.dlg.comboBoxFeicao.clear()

        
        for layer in QgsProject.instance().mapLayers().values():
        
            if layer.type() == QgsMapLayerType.Vector:
                if layer.geometryType() == 1:  # linha
                    self.dlg.comboBoxCamada.addItem(
                        layer.name(),
                        layer.id()
                    )

            if layer.type() == QgsMapLayerType.Raster:
                
                self.dlg.comboBoxDEM.addItem(
                        layer.name(),
                        layer.id()
                )

        layer_id = self.dlg.comboBoxCamada.currentData()

        camada = QgsProject.instance().mapLayer(layer_id)

        indice_nome = camada.fields().indexOf("Name")

        for feicao in camada.getFeatures():
                    nome = feicao[indice_nome]
        
                    if nome is not None:
                        self.dlg.comboBoxFeicao.addItem(
                            str(nome),
                            feicao.id()
                        )

          
        self.dlg.show()
            
        result = self.dlg.exec_()


       
        if result:
            
            print("Iniciando")

            

            layer_id_dem = self.dlg.comboBoxDEM.currentData()

            

            raster = QgsProject.instance().mapLayer(layer_id_dem)

            # Pega os valores da interface
            distancia = self.dlg.doubleSpinBoxDistancia.value()

            arquivo = self.dlg.lineEditArquivo.text()

            arquivo_geojson = self.getGJPath(arquivo)

            fid = self.dlg.comboBoxFeicao.currentData()

            camada.selectByIds([fid])

            name = self.dlg.comboBoxFeicao.currentText()

            resultado = processing.run(
                "native:pointsalonglines",
                {
                    'INPUT': QgsProcessingFeatureSourceDefinition(
                        camada.id(),
                        selectedFeaturesOnly=True
                    ),
                    'DISTANCE':distancia,
                    'START_OFFSET':0,
                    'END_OFFSET':0,
                    'OUTPUT': 'TEMPORARY_OUTPUT'
                }
            )

            camada_temp = resultado['OUTPUT']

            final = processing.run(
                "native:setzfromraster",
                {
                     'INPUT':camada_temp,
                     'RASTER':raster,
                     'BAND':1,
                     'NODATA':None,
                     'SCALE':1,
                     'OFFSET':0,
                     'OUTPUT': arquivo_geojson
                }
            )

            caminho_geojson = final['OUTPUT']

            self.GerarPos(caminho_geojson, arquivo)

            QgsProject.instance().addMapLayer(
                QgsVectorLayer(
                    final['OUTPUT'],
                    "Pontos " + name,
                    "ogr"
                )
            )


            self.iface.messageBar().pushInfo(
                        ".POS Export",
                        "Arquivo .pos exportado!"
                    )

            camada.removeSelection()
